In [1]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [2]:
test = np.load('test_eigs.npz')

In [3]:
test.keys()

['pos_evals', 'neg_evals']

In [4]:
test['neg_evals']

array([-137.89653181])

In [5]:
test['pos_evals']

array([17318.291], dtype=float32)

In [6]:
train = np.load('train_eigs.npz')

In [7]:
train['neg_evals']

array([-290.61898138])

In [8]:
train['pos_evals']

array([3617.2668], dtype=float32)